title: Christian Bäuerlein
email: fabrik42@gmail.com
ga_tracking_code: 'UA-88267814-1'
description: >
  Hi! My name is Christian Bäuerlein,
  a software developer living near Frankfurt in Germany.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

sass:
    sass_dir: css
    style: compressed
